### ISSUE TITLE
aegir.local not accessible after reboot

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/vagrant-aegir#3]
After a successful installation using the procedure mentioned in readme, i shutdown my notebook.

Then i rebooted it the next day and went on to execute
'vagrant reload'
followed by 
'vagrant provisions'
in the terminal.

Both the commands executed but i was not able to access aegir.local anymore.

I am pasting a screenshot of my terminal output for reference if that may help.

![1__bash](https://f.cloud.github.com/assets/1006481/1972954/37d75b18-8351-11e3-9a9b-7fbfb7810012.png)

Any help is much appreciated.

Thank you in advance.

**Comment by d34dman** [comment]
thanks @MuschPusch was able to get it up and running by doing the following.
1. vagrant up
2. vagrant ssh
3. apache2ctl start

NOTE:
before step 3, running 'service apache2 status' in command line had told me "Apache2 is NOT running."

**Comment by MuschPusch** [comment]
This is due to the problem that sometimes NFS is started after the apache service is started. (the htaccess on the shared volume is missing -> error in apache2ctl start). I thought i fixed this by adding a delay on starting apache2 but sometimes this still seems to happen. I will find a fix for this one of the next days...

**Comment by MuschPusch** [comment]
This should be fixed with some lame workaround:  1e26f065dbfd584b50b3a5d1982b0cfd5910cb5f
